- op: add
  path: /spec/template
  value: {}
- op: move
  from: /spec/jobTemplate/spec/template/spec
  path: /spec/template/spec
- op: remove
  path: /spec/jobTemplate
- op: remove
  path: /spec/schedule
- op: remove
  path: /spec/suspend
- op: remove
  path: /spec/timeZone
- op: remove
  path: /spec/startingDeadlineSeconds
- op: remove
  path: /spec/concurrencyPolicy
- op: replace
  path: /kind
  value: Job
